service: twitter-bot-serverless
frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs14.x

plugins: 
  - serverless-offline


functions:
  tweetDeclarations:
    handler: src/handlers/tweetDeclarations.handler
    events:
      - schedule: rate(10 hours)
  searchAndReply:
    handler: src/handlers/searchAndReply.handler
    events:
      - schedule: rate(30 minutes)